### ISSUE TITLE
The site isn't showing...

### ISSUE THREAD

**Issue by jonjondev** [naggr/naggr.github.io#1]
Seems to have the right project name and it uses an index.html so I'm a bit stumped...

**Comment by SamuelMarks** [comment]
Agreed, it doesn't make sense:

<img width="764" alt="screen shot of settings page" src="https://user-images.githubusercontent.com/807580/42427606-be6094e4-8372-11e8-9f38-613c84028dc5.png">

Maybe the build processor hung, and we should just push another commit?

**Comment by jonjondev** [comment]
Just pushed a commit and it's up, closing the issue here.
